# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: docker login -u $(dockerId) -p $(pswd)
      - script: docker build -t $(dockerId)/$(imageName) .  # add options to this command to meet your needs
      - task: Docker@2
        displayName: Build an image
        inputs:
          command: build
          dockerfile: '**/Dockerfile'
          tags: |
            $(tag)